
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.cicciotecchio.yaspl.parser;

/** CUP generated interface containing symbol constants. */
public interface LexerSym {
  /* terminals */
  public static final int CHAR_CONST = 27;
  public static final int LGPAR = 15;
  public static final int CHAR = 9;
  public static final int GE = 38;
  public static final int UMINUS = 49;
  public static final int DOUBLE_CONST = 25;
  public static final int DOUBLE = 7;
  public static final int SEMI = 5;
  public static final int INT = 48;
  public static final int OUT = 46;
  public static final int FOR = 33;
  public static final int MINUS = 20;
  public static final int WRITE = 18;
  public static final int INOUT = 47;
  public static final int AND = 43;
  public static final int NOT = 42;
  public static final int LT = 39;
  public static final int RPAR = 14;
  public static final int IN = 45;
  public static final int OR = 44;
  public static final int BOOL = 6;
  public static final int RGPAR = 16;
  public static final int COMMA = 11;
  public static final int INC = 50;
  public static final int DIV = 22;
  public static final int PLUS = 19;
  public static final int ASSIGN = 30;
  public static final int IF = 31;
  public static final int ID = 10;
  public static final int LE = 40;
  public static final int EOF = 0;
  public static final int INT_CONST = 24;
  public static final int TRUE = 28;
  public static final int error = 1;
  public static final int MOD = 23;
  public static final int START = 3;
  public static final int EQ = 41;
  public static final int HEAD = 2;
  public static final int TIMES = 21;
  public static final int COLON = 4;
  public static final int ELSE = 36;
  public static final int READ = 17;
  public static final int WHILE = 34;
  public static final int THEN = 32;
  public static final int LPAR = 13;
  public static final int STRING = 8;
  public static final int DEF = 12;
  public static final int DEC = 51;
  public static final int FALSE = 29;
  public static final int STRING_CONST = 26;
  public static final int GT = 37;
  public static final int DO = 35;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "HEAD",
  "START",
  "COLON",
  "SEMI",
  "BOOL",
  "DOUBLE",
  "STRING",
  "CHAR",
  "ID",
  "COMMA",
  "DEF",
  "LPAR",
  "RPAR",
  "LGPAR",
  "RGPAR",
  "READ",
  "WRITE",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIV",
  "MOD",
  "INT_CONST",
  "DOUBLE_CONST",
  "STRING_CONST",
  "CHAR_CONST",
  "TRUE",
  "FALSE",
  "ASSIGN",
  "IF",
  "THEN",
  "FOR",
  "WHILE",
  "DO",
  "ELSE",
  "GT",
  "GE",
  "LT",
  "LE",
  "EQ",
  "NOT",
  "AND",
  "OR",
  "IN",
  "OUT",
  "INOUT",
  "INT",
  "UMINUS",
  "INC",
  "DEC"
  };
}

